/**
 * EmailJS service for sending shopping lists
 */

import { uploadShoppingListFile, isStorageAvailable, initializeShoppingListState } from './storageService';
import { getSupabaseClient, isSupabaseConfigured } from './supabaseClient';

/**
 * Generate shopping list attachment optimized for Apple Notes and Google Keep
 * Format: Markdown with checkboxes that can be easily imported into both apps
 */
export function generateShoppingListAttachment({
  weekRange,
  schedule,
  shoppingListMarkdown,
}) {
  // Create a clean markdown format optimized for Apple Notes and Google Keep
  let attachment = `# Shopping List\n\n`;
  attachment += `Week of ${weekRange}\n\n`;
  
  if (schedule && schedule.length > 0) {
    attachment += `## Recipes This Week\n\n`;
    schedule.forEach(({ day, cook, recipe }) => {
      attachment += `- ${recipe} (${cook} - ${day})\n`;
    });
    attachment += `\n`;
  }
  
  // Extract the categorized ingredients from markdown
  // The markdown already has the format we want with checkboxes
  if (shoppingListMarkdown) {
    const lines = shoppingListMarkdown.split('\n');
    let captureIngredients = false;
    
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      
      // Start capturing from the first category section
      if (line.startsWith('### ') && (line.includes('All Ingredients') || !line.includes('Recipes This Week'))) {
        captureIngredients = true;
      }
      
      // Capture all ingredient lines (categories and items with checkboxes)
      if (captureIngredients) {
        // Skip the main header if we encounter it again
        if (line.startsWith('# ') && line.includes('Shopping List')) {
          continue;
        }
        if (line.startsWith('## ') && line.includes('Week of')) {
          continue;
        }
        attachment += line + '\n';
      }
    }
  }
  
  attachment += `\n---\n`;
  attachment += `Generated by Babe, What's for Dinner?\n`;
  attachment += `Copy this into Apple Notes or Google Keep for an interactive shopping list.\n`;
  
  return attachment;
}

/**
 * Convert text to base64 for EmailJS attachment
 */
function textToBase64(text) {
  // Convert to base64
  const base64 = btoa(unescape(encodeURIComponent(text)));
  return base64;
}

/**
 * Parse shopping list markdown into structured data
 * Returns items with categories for interactive list
 */
function parseShoppingListMarkdown(markdown) {
  const items = [];
  const lines = markdown.split('\n');
  let currentCategory = null;
  let recipes = [];

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    
    // Extract recipes section
    if (line.startsWith('### Recipes This Week:') || line.startsWith('## Recipes This Week')) {
      // Skip recipes section - we'll extract it separately
      continue;
    }
    
    // Extract recipe items
    if (line.match(/^-\s+[^(]+\s+\([^)]+\)$/)) {
      // Format: "- Recipe Name (Cook - Day)"
      const match = line.match(/^-\s+(.+?)\s+\((.+?)\s+-\s+(.+?)\)$/);
      if (match) {
        recipes.push({
          recipe: match[1],
          cook: match[2],
          day: match[3],
        });
      }
      continue;
    }
    
    // Category header
    if (line.startsWith('### ')) {
      currentCategory = line.substring(4).trim();
      continue;
    }
    
    // Shopping list item with checkbox
    if (line.match(/^-\s+\[\s*\]\s+/)) {
      const itemText = line.replace(/^-\s+\[\s*\]\s+/, '').trim();
      if (itemText) {
        // Create unique item ID from text (simple hash)
        const itemId = btoa(itemText).replace(/[+/=]/g, '').substring(0, 20);
        items.push({
          item_id: itemId,
          item_text: itemText,
          category: currentCategory || 'Other',
        });
      }
    }
  }

  return { items, recipes };
}

/**
 * Generate unique list ID
 */
function generateListId(weekRange) {
  const timestamp = Date.now();
  const random = Math.random().toString(36).substring(2, 8);
  const weekHash = btoa(weekRange).replace(/[+/=]/g, '').substring(0, 8);
  return `list-${timestamp}-${weekHash}-${random}`;
}

/**
 * Send shopping list email via EmailJS
 */
export async function sendShoppingListEmail({
  toEmails,
  weekRange,
  schedule,
  shoppingListHtml,
  shoppingListText,
  shoppingListMarkdown,
  emailjsServiceId,
  emailjsTemplateId,
  emailjsPublicKey,
  supabaseUrl = '',
  supabaseAnonKey = '',
  includeAttachment = true,
}) {
  if (!emailjsServiceId || !emailjsTemplateId || !emailjsPublicKey) {
    throw new Error('EmailJS credentials are required');
  }

  // Validate credentials are not just whitespace
  if (!emailjsServiceId.trim() || !emailjsTemplateId.trim() || !emailjsPublicKey.trim()) {
    throw new Error('EmailJS credentials cannot be empty');
  }

  if (!toEmails || toEmails.length === 0) {
    throw new Error('At least one email address is required');
  }

  // Validate email addresses
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  const invalidEmails = toEmails.filter(email => !emailRegex.test(email));
  if (invalidEmails.length > 0) {
    throw new Error(`Invalid email addresses: ${invalidEmails.join(', ')}`);
  }

  // Generate attachment if requested
  let attachmentBase64 = null;
  let attachmentContent = null;
  if (includeAttachment && shoppingListMarkdown) {
    attachmentContent = generateShoppingListAttachment({
      weekRange,
      schedule,
      shoppingListMarkdown,
    });
    attachmentBase64 = textToBase64(attachmentContent);
  }

  // Upload markdown file and copy page to Supabase Storage if available (for working download links)
  let markdownFileUrl = null;
  let interactiveListUrl = null;
  let storageError = null;
  
  if (attachmentContent && isStorageAvailable()) {
    const filename = `shopping-list-${weekRange.replace(/\s+/g, '-').toLowerCase()}.md`;
    
    // Upload markdown file
    const markdownResult = await uploadShoppingListFile(attachmentContent, filename, 'text/markdown');
    if (markdownResult.success) {
      markdownFileUrl = markdownResult.url;
    } else {
      storageError = markdownResult.error;
      console.warn('Failed to upload markdown file to Supabase Storage:', markdownResult.error);
    }
    
    // Generate interactive shopping list with Vercel-hosted page
    if (attachmentContent && shoppingListMarkdown && isSupabaseConfigured()) {
      try {
        // Parse shopping list markdown into structured data
        const parsed = parseShoppingListMarkdown(shoppingListMarkdown);
        
        // Convert to itemsByCategory format for interactive list
        const itemsByCategory = {};
        parsed.items.forEach(item => {
          if (!itemsByCategory[item.category]) {
            itemsByCategory[item.category] = [];
          }
          itemsByCategory[item.category].push(item.item_text);
        });
        
        // Generate unique list ID
        const listId = generateListId(weekRange);
        
        // Store list data in Supabase for the Vercel-hosted page to fetch
        const supabase = getSupabaseClient();
        if (supabase) {
          const { error: insertError } = await supabase
            .from('shopping_list_data')
            .upsert({
              list_id: listId,
              week_range: weekRange,
              schedule: schedule.map(s => ({
                recipe: s.recipe,
                cook: s.cook,
                day: s.day,
              })),
              items_by_category: itemsByCategory,
            }, {
              onConflict: 'list_id',
            });
          
          if (insertError) {
            console.error('Error storing shopping list data:', insertError);
          } else {
            // Generate URL to Vercel-hosted shopping list page
            // Include Supabase credentials so the page can fetch from the correct project
            const baseUrl = typeof window !== 'undefined' && window.location.origin 
              ? window.location.origin 
              : 'https://meal-prep-recipes.vercel.app';
            
            // Build URL with all needed parameters (using passed Supabase credentials)
            const params = new URLSearchParams({
              id: listId,
              url: supabaseUrl?.trim() || '',
              key: supabaseAnonKey?.trim() || '',
            });
            interactiveListUrl = `${baseUrl}/shopping-list.html?${params.toString()}`;
            console.log('Interactive shopping list URL:', interactiveListUrl);
          }
        }
        
        // Initialize state in Supabase if available
        if (parsed.items.length > 0) {
          await initializeShoppingListState(listId, parsed.items);
        }
      } catch (error) {
        console.error('Error generating interactive shopping list:', error);
      }
    }
    
  }

  // EmailJS doesn't support multiple recipients in one call, so we send to each
  const results = await Promise.allSettled(
    toEmails.map(async (email) => {
      try {
        // Build template params
        const templateParams = {
          to_email: email,
          subject: `This Week's Plan - Week of ${weekRange}`,
          week_range: weekRange,
          schedule_table: formatScheduleTable(schedule),
          shopping_list_html: shoppingListHtml,
          shopping_list_text: shoppingListText,
          shopping_list_markdown: shoppingListMarkdown,
          item_count: countShoppingListItems(shoppingListText),
          recipe_count: schedule.length,
        };

        // Add attachment content for easy copying into Apple Notes/Google Keep
        // This will be included in the email body as a formatted text block
        if (attachmentContent) {
          // Escape HTML for safe display in email
          const escapeHtml = (text) => {
            return text
              .replace(/&/g, '&amp;')
              .replace(/</g, '&lt;')
              .replace(/>/g, '&gt;')
              .replace(/"/g, '&quot;')
              .replace(/'/g, '&#039;');
          };
          
          // Convert markdown to HTML for email display
          const markdownToHtml = (md) => {
            return md
              .replace(/^# (.*$)/gim, '<h1 style="font-size: 20px; font-weight: bold; margin-top: 20px; margin-bottom: 10px;">$1</h1>')
              .replace(/^## (.*$)/gim, '<h2 style="font-size: 18px; font-weight: bold; margin-top: 16px; margin-bottom: 8px;">$1</h2>')
              .replace(/^### (.*$)/gim, '<h3 style="font-size: 16px; font-weight: bold; margin-top: 12px; margin-bottom: 6px;">$1</h3>')
              .replace(/^- \[ \] (.*$)/gim, '<div style="margin: 4px 0; padding-left: 20px;">☐ $1</div>')
              .replace(/^- (.*$)/gim, '<div style="margin: 4px 0; padding-left: 20px;">• $1</div>')
              .replace(/\n\n/g, '<br><br>')
              .replace(/\n/g, '<br>');
          };
          
          templateParams.shopping_list_attachment_text = attachmentContent;
          templateParams.shopping_list_attachment_html = markdownToHtml(attachmentContent);
          
          // Use Supabase Storage URLs if available (works in all email clients)
          // Otherwise, fall back to copy-paste section only
          const filename = `shopping-list-${weekRange.replace(/\s+/g, '-').toLowerCase()}.md`;
          
          if (markdownFileUrl) {
            // Real download links that work in all email clients
            templateParams.shopping_list_download_link = markdownFileUrl;
            templateParams.shopping_list_download_filename = filename;
            templateParams.download_section_message = 'Download your shopping list as a file. Click the button below to download.';
          } else {
            // No download links available (Supabase not configured or upload failed)
            templateParams.shopping_list_download_link = '';
            templateParams.shopping_list_download_filename = '';
            templateParams.download_section_message = 'To enable file downloads, please configure Supabase in your app Settings. For now, use the copy option below to get your shopping list.';
            if (storageError) {
              templateParams.storage_error_message = storageError;
            }
          }
          
          // Add interactive list URL
          if (interactiveListUrl) {
            templateParams.copy_page_url = interactiveListUrl;
            templateParams.has_interactive_list = true;
          } else {
            templateParams.copy_page_url = '';
            templateParams.has_interactive_list = false;
          }
          
          // Also provide base64 for EmailJS dynamic attachment (requires paid plan + template configuration)
          // The parameter name 'shopping_list_attachment' must match the Parameter Name in EmailJS template's Attachments tab
          if (attachmentBase64) {
            templateParams.shopping_list_attachment = attachmentBase64;
            templateParams.shopping_list_attachment_filename = filename;
          }
        } else {
          // No attachment content
          templateParams.shopping_list_download_link = '';
          templateParams.download_section_message = 'To enable file downloads, please configure Supabase in your app Settings. For now, use the copy option below to get your shopping list.';
        }

        const response = await fetch(`https://api.emailjs.com/api/v1.0/email/send`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            service_id: emailjsServiceId,
            template_id: emailjsTemplateId,
            user_id: emailjsPublicKey,
            template_params: templateParams,
          }),
        });

        // Check response status first
        if (response.status !== 200) {
          // EmailJS returns plain text errors for 422, not JSON
          let errorText = '';
          try {
            errorText = await response.text();
          } catch (e) {
            errorText = `HTTP ${response.status}`;
          }
          
          // Log raw response for debugging
          console.error('EmailJS error response:', {
            status: response.status,
            rawResponse: errorText,
            email,
            serviceId: emailjsServiceId,
            templateId: emailjsTemplateId,
          });
          
          // Check for recipient-related errors (422 typically means template configuration issue)
          const lowerErrorText = errorText.toLowerCase();
          if (response.status === 422 || lowerErrorText.includes('recipient') || lowerErrorText.includes('to_email')) {
            throw new Error(
              `EmailJS template configuration error for ${email}: ${errorText}. ` +
              `Make sure your EmailJS template's "To Email" field is set to {{to_email}}. ` +
              `See EMAILJS_TEMPLATE_SETUP.md for instructions.`
            );
          }
          
          throw new Error(`EmailJS error for ${email}: ${errorText}`);
        }
        
        // Parse JSON response (only if status is 200)
        // EmailJS may return non-JSON even on 200, so handle both cases
        let responseData;
        let responseText = '';
        
        try {
          // Try to get text first to handle both JSON and plain text responses
          responseText = await response.text();
          
          // Try to parse as JSON
          try {
            responseData = JSON.parse(responseText);
          } catch (parseError) {
            // If it's not JSON, treat the text as the response
            console.error('EmailJS non-JSON response (status 200):', {
              rawResponse: responseText,
              email,
            });
            // If status is 200 but response isn't JSON, check if it's an error message
            const lowerText = responseText.toLowerCase();
            if (lowerText.includes('recipient') || lowerText.includes('to_email') || lowerText.includes('error')) {
              throw new Error(
                `EmailJS template configuration error for ${email}: ${responseText}. ` +
                `Make sure your EmailJS template's "To Email" field is set to {{to_email}}. ` +
                `See EMAILJS_TEMPLATE_SETUP.md for instructions.`
              );
            }
            // If it's not an obvious error, assume success (some EmailJS responses are plain text "OK")
            if (responseText.trim().toUpperCase() === 'OK') {
              console.log('EmailJS success for:', email);
              return { email, success: true };
            }
            throw new Error(`EmailJS returned unexpected response format for ${email}: ${responseText}`);
          }
        } catch (textError) {
          // If we can't even get text, it's a network/response error
          console.error('EmailJS response read error:', textError);
          throw new Error(`Failed to read EmailJS response for ${email}: ${textError.message}`);
        }
        
        // Check if the JSON response indicates success
        if (responseData.status !== 200 || responseData.text !== 'OK') {
          const errorMessage = responseData.text || responseData.message || `HTTP ${response.status}`;
          console.error('EmailJS error response:', {
            status: response.status,
            responseData,
            email,
            serviceId: emailjsServiceId,
            templateId: emailjsTemplateId,
          });
          
          // Check for recipient-related errors in JSON response
          const lowerErrorMessage = (errorMessage || '').toLowerCase();
          if (lowerErrorMessage.includes('recipient') || lowerErrorMessage.includes('to_email')) {
            throw new Error(
              `EmailJS template configuration error for ${email}: ${errorMessage}. ` +
              `Make sure your EmailJS template's "To Email" field is set to {{to_email}}. ` +
              `See EMAILJS_TEMPLATE_SETUP.md for instructions.`
            );
          }
          
          throw new Error(`EmailJS error for ${email}: ${errorMessage}`);
        }

        console.log('EmailJS success for:', email);
        return { email, success: true };
      } catch (error) {
        // If it's already our formatted error, rethrow it
        if (error.message && (error.message.includes('EmailJS error') || error.message.includes('EmailJS template configuration'))) {
          throw error;
        }
        // Otherwise, wrap it with context
        console.error('EmailJS fetch error:', error);
        throw new Error(`Failed to send email to ${email}: ${error.message}`);
      }
    })
  );

  const successful = results.filter(r => r.status === 'fulfilled').length;
  const failed = results.filter(r => r.status === 'rejected');

  if (failed.length > 0) {
    console.error('Some emails failed to send:', failed.map(f => ({
      reason: f.reason?.message || f.reason,
      email: f.reason?.email || 'unknown',
    })));
  }

  return {
    successful,
    total: toEmails.length,
    failed: failed.length,
    errors: failed.map(f => ({
      email: f.reason?.email || 'unknown',
      error: f.reason?.message || String(f.reason),
    })),
  };
}

/**
 * Format schedule as HTML table with app branding
 */
function formatScheduleTable(schedule) {
  if (!schedule || schedule.length === 0) {
    return '<p style="color: #737373; font-family: Inter, system-ui, sans-serif; margin: 20px 0;">No meals scheduled.</p>';
  }

  // Primary blue: hsl(221 83% 53%) = #3b82f6
  // Border: hsl(0 0% 89.8%) = #e5e5e5
  // Muted text: hsl(0 0% 45.1%) = #737373
  // Background: hsl(0 0% 96.1%) = #f5f5f5

  let html = '<table style="border-collapse: collapse; width: 100%; margin: 24px 0; border: 1px solid #e5e5e5; border-radius: 8px; overflow: hidden;">';
  html += '<thead><tr style="background-color: #f5f5f5;">';
  html += '<th style="border-bottom: 1px solid #e5e5e5; padding: 14px 16px; text-align: left; font-family: \'JetBrains Mono\', \'Fira Code\', Consolas, Monaco, monospace; font-size: 13px; font-weight: 600; color: #0a0a0a; letter-spacing: -0.02em;">Day</th>';
  html += '<th style="border-bottom: 1px solid #e5e5e5; padding: 14px 16px; text-align: left; font-family: \'JetBrains Mono\', \'Fira Code\', Consolas, Monaco, monospace; font-size: 13px; font-weight: 600; color: #0a0a0a; letter-spacing: -0.02em;">Cook</th>';
  html += '<th style="border-bottom: 1px solid #e5e5e5; padding: 14px 16px; text-align: left; font-family: \'JetBrains Mono\', \'Fira Code\', Consolas, Monaco, monospace; font-size: 13px; font-weight: 600; color: #0a0a0a; letter-spacing: -0.02em;">Recipe</th>';
  html += '</tr></thead><tbody>';

  schedule.forEach(({ day, cook, recipe }, index) => {
    const bgColor = index % 2 === 0 ? '#ffffff' : '#fafafa';
    html += `<tr style="background-color: ${bgColor};">`;
    html += `<td style="border-bottom: 1px solid #e5e5e5; padding: 12px 16px; font-family: Inter, system-ui, sans-serif; color: #0a0a0a;">${day}</td>`;
    html += `<td style="border-bottom: 1px solid #e5e5e5; padding: 12px 16px; font-family: Inter, system-ui, sans-serif; color: #0a0a0a;">${cook}</td>`;
    html += `<td style="border-bottom: 1px solid #e5e5e5; padding: 12px 16px; font-family: Inter, system-ui, sans-serif; color: #0a0a0a; font-weight: 500;">${recipe}</td>`;
    html += '</tr>';
  });

  html += '</tbody></table>';
  return html;
}

/**
 * Generate branded email HTML template
 * This function returns the HTML structure that should be used in EmailJS template
 */
export function getBrandedEmailTemplate() {
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    body {
      font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif;
      background-color: #fafafa;
      color: #0a0a0a;
      line-height: 1.6;
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
    }
    .email-container {
      max-width: 600px;
      margin: 0 auto;
      background-color: #ffffff;
    }
    .header {
      background-color: #ffffff;
      border-bottom: 1px solid #e5e5e5;
      padding: 32px 24px;
      text-align: left;
    }
    .header h1 {
      font-family: 'JetBrains Mono', 'Fira Code', Consolas, Monaco, monospace;
      font-size: 24px;
      font-weight: 700;
      color: #0a0a0a;
      letter-spacing: -0.02em;
      margin-bottom: 4px;
    }
    .header p {
      font-size: 14px;
      color: #737373;
      margin: 0;
    }
    .content {
      padding: 32px 24px;
    }
    .section {
      margin-bottom: 32px;
    }
    .section:last-child {
      margin-bottom: 0;
    }
    .section-title {
      font-family: 'JetBrains Mono', 'Fira Code', Consolas, Monaco, monospace;
      font-size: 16px;
      font-weight: 600;
      color: #0a0a0a;
      letter-spacing: -0.02em;
      margin-bottom: 16px;
      padding-bottom: 8px;
      border-bottom: 2px solid #0a0a0a;
    }
    .stats {
      display: inline-block;
      background-color: #f5f5f5;
      padding: 6px 12px;
      border-radius: 4px;
      font-size: 13px;
      color: #737373;
      margin-bottom: 16px;
    }
    .footer {
      background-color: #ffffff;
      border-top: 1px solid #e5e5e5;
      padding: 24px;
      text-align: center;
    }
    .footer p {
      font-family: 'JetBrains Mono', 'Fira Code', Consolas, Monaco, monospace;
      font-size: 12px;
      color: #737373;
      margin: 4px 0;
    }
    .footer .version {
      font-size: 11px;
      color: #a3a3a3;
    }
    table {
      border-collapse: collapse;
      width: 100%;
      margin: 24px 0;
      border: 1px solid #e5e5e5;
      border-radius: 8px;
      overflow: hidden;
    }
    th {
      border-bottom: 1px solid #e5e5e5;
      padding: 14px 16px;
      text-align: left;
      font-family: 'JetBrains Mono', 'Fira Code', Consolas, Monaco, monospace;
      font-size: 13px;
      font-weight: 600;
      color: #0a0a0a;
      letter-spacing: -0.02em;
      background-color: #f5f5f5;
    }
    td {
      border-bottom: 1px solid #e5e5e5;
      padding: 12px 16px;
      font-family: Inter, system-ui, sans-serif;
      color: #0a0a0a;
    }
    tr:last-child td {
      border-bottom: none;
    }
    tr:nth-child(even) {
      background-color: #fafafa;
    }
    @media only screen and (max-width: 600px) {
      .email-container {
        width: 100% !important;
      }
      .header, .content, .footer {
        padding: 24px 16px !important;
      }
    }
  </style>
</head>
<body>
  <div class="email-container">
    <!-- Header -->
    <div class="header">
      <h1>Babe, What's for Dinner?</h1>
      <p>Finally, an answer.</p>
    </div>
    
    <!-- Content -->
    <div class="content">
      <!-- Week Range -->
      <div class="section">
        <div class="stats">Week of {{week_range}}</div>
      </div>
      
      <!-- Schedule -->
      <div class="section">
        <h2 class="section-title">This Week's Schedule</h2>
        {{{schedule_table}}}
      </div>
      
      <!-- Shopping List -->
      <div class="section">
        <h2 class="section-title">Shopping List</h2>
        <div class="stats">{{item_count}} items • {{recipe_count}} recipes</div>
        <div style="margin-top: 16px;">
          {{{shopping_list_html}}}
        </div>
      </div>
      
      <!-- Download Shopping List -->
      <div class="section" style="margin-top: 32px; padding-top: 24px; border-top: 2px solid #e5e5e5;">
        <h2 class="section-title">Download Shopping List</h2>
        <p style="color: #737373; font-size: 14px; margin-bottom: 16px;">
          {{download_section_message}}
        </p>
        <div style="text-align: center; margin: 20px 0;">
          <a href="{{shopping_list_download_link}}" target="_blank" style="display: inline-block; background-color: #3b82f6; color: #ffffff; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: 600; font-family: Inter, system-ui, sans-serif; font-size: 14px; margin: 4px;">
            📥 Download as Markdown
          </a>
        </div>
        <p style="color: #737373; font-size: 12px; margin-top: 12px; font-style: italic;">
          <strong>Tip:</strong> Click the button above to download your shopping list. The file will open in your browser - you can then save it to your device.
        </p>
        <p style="color: #737373; font-size: 12px; margin-top: 8px; font-style: italic;">
          {{storage_error_message}}
        </p>
      </div>
      
      <!-- Interactive Shopping List -->
      <div class="section" style="margin-top: 32px; padding-top: 24px; border-top: 2px solid #e5e5e5;">
        <h2 class="section-title">Interactive Shopping List</h2>
        <p style="color: #737373; font-size: 14px; margin-bottom: 16px;">
          Open your interactive shopping list to check off items while shopping. Tap items to cross them off, add new items, and share with family. Works offline and syncs across devices!
        </p>
        <div style="text-align: center; margin: 20px 0;">
          <a href="{{copy_page_url}}" target="_blank" style="display: inline-block; background-color: #10b981; color: #ffffff; padding: 14px 28px; text-decoration: none; border-radius: 8px; font-weight: 600; font-family: Inter, system-ui, sans-serif; font-size: 16px; box-shadow: 0 4px 6px rgba(16, 185, 129, 0.3);">
            🛒 Open Interactive Shopping List
          </a>
        </div>
        <p style="color: #737373; font-size: 12px; margin-top: 12px; text-align: center; font-style: italic;">
          Click the button above to open your interactive shopping list. Tap items to check them off, add new items on the fly, and share with others. Works on mobile and desktop!
        </p>
        <div style="background-color: #f5f5f5; padding: 16px; border-radius: 8px; font-family: 'JetBrains Mono', 'Fira Code', Consolas, Monaco, monospace; font-size: 13px; white-space: pre-wrap; overflow-x: auto; border: 1px solid #e5e5e5; margin-top: 16px;">
          {{shopping_list_attachment_text}}
        </div>
        <p style="color: #737373; font-size: 12px; margin-top: 12px; font-style: italic;">
          Or manually select all text in the box above, copy it, and paste it into a new note in Apple Notes or Google Keep. The checkboxes will work as interactive lists.
        </p>
      </div>
    </div>
    
    <!-- Footer -->
    <div class="footer">
      <p>Babe, What's for Dinner?</p>
      <p class="version">v1.0.0 • Made with love (and mild guilt)</p>
    </div>
  </div>
</body>
</html>`;
}

/**
 * Count items in shopping list
 */
function countShoppingListItems(shoppingListText) {
  if (!shoppingListText) return 0;
  // Count lines that look like list items (start with - or *)
  const matches = shoppingListText.match(/^[-*]\s+/gm);
  return matches ? matches.length : 0;
}


