/**
 * Meal Plan Markdown Generator
 *
 * Generates GitHub Flavored Markdown exports for weekly meal plans,
 * including the schedule table and full recipe details.
 */

import type { DayOfWeek } from "@/types/meal-plan";
import {
  createMarkdownHeading,
  createMarkdownTable,
  createMarkdownList,
  createMarkdownHorizontalRule,
  bold,
  italic,
  joinSections,
  downloadMarkdownFile,
  formatDateRangeForFilename,
} from "./markdown-generator";

/**
 * Recipe data needed for meal plan export
 */
export interface MealPlanRecipe {
  id: string;
  title: string;
  recipe_type: string;
  prep_time: string | null;
  cook_time: string | null;
  ingredients: string[];
  instructions: string[];
}

/**
 * Assignment data for meal plan export
 */
export interface MealPlanAssignment {
  recipe: MealPlanRecipe;
  cook: string | null;
  day_of_week: DayOfWeek;
}

export interface MealPlanMarkdownOptions {
  weekRange: string;
  assignments: MealPlanAssignment[];
  includeFullRecipes?: boolean;
}

const DAYS_ORDER: DayOfWeek[] = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
  "Sunday",
];

/**
 * Generate complete markdown document for a meal plan
 */
export function generateMealPlanMarkdown(options: MealPlanMarkdownOptions): string {
  const { weekRange, assignments, includeFullRecipes = true } = options;
  const sections: string[] = [];

  // Title
  sections.push(createMarkdownHeading(`Meal Plan: ${weekRange}`, 1));

  // Group assignments by day
  const byDay = groupAssignmentsByDay(assignments);

  // Weekly schedule table
  const scheduleTable = formatWeekScheduleTable(byDay);
  sections.push(scheduleTable);

  // Shopping list (combined ingredients from all recipes)
  const shoppingSection = formatCombinedShoppingList(assignments);
  if (shoppingSection) {
    sections.push(shoppingSection);
  }

  // Full recipes section
  if (includeFullRecipes) {
    const recipesSection = formatFullRecipesSection(byDay);
    if (recipesSection) {
      sections.push(recipesSection);
    }
  }

  // Footer
  sections.push(
    joinSections(
      createMarkdownHorizontalRule(),
      italic("Generated by MealPrepRecipes")
    )
  );

  return joinSections(...sections);
}

/**
 * Group assignments by day of week
 */
function groupAssignmentsByDay(
  assignments: MealPlanAssignment[]
): Record<DayOfWeek, MealPlanAssignment[]> {
  const byDay: Record<DayOfWeek, MealPlanAssignment[]> = {
    Monday: [],
    Tuesday: [],
    Wednesday: [],
    Thursday: [],
    Friday: [],
    Saturday: [],
    Sunday: [],
  };

  assignments.forEach((assignment) => {
    byDay[assignment.day_of_week].push(assignment);
  });

  return byDay;
}

/**
 * Format the weekly schedule as a GFM table
 */
export function formatWeekScheduleTable(
  byDay: Record<DayOfWeek, MealPlanAssignment[]>
): string {
  const heading = createMarkdownHeading("Weekly Schedule", 2);

  const rows: { Day: string; Recipe: string; Cook: string }[] = [];

  DAYS_ORDER.forEach((day) => {
    const dayAssignments = byDay[day];
    if (dayAssignments.length === 0) {
      rows.push({ Day: day, Recipe: "-", Cook: "-" });
    } else {
      dayAssignments.forEach((assignment, index) => {
        rows.push({
          Day: index === 0 ? day : "",
          Recipe: assignment.recipe.title,
          Cook: assignment.cook || "-",
        });
      });
    }
  });

  const table = createMarkdownTable(["Day", "Recipe", "Cook"], rows);
  return joinSections(heading, table);
}

/**
 * Format combined shopping list from all recipes
 */
function formatCombinedShoppingList(assignments: MealPlanAssignment[]): string | null {
  const allIngredients = new Set<string>();

  assignments.forEach((assignment) => {
    if (assignment.recipe.ingredients) {
      assignment.recipe.ingredients.forEach((ing) => allIngredients.add(ing));
    }
  });

  if (allIngredients.size === 0) return null;

  const heading = createMarkdownHeading("Shopping List", 2);
  const ingredientsList = Array.from(allIngredients);

  // Create checkbox list
  const checkboxes = ingredientsList
    .map((ing) => `- [ ] ${ing}`)
    .join("\n");

  return joinSections(heading, checkboxes);
}

/**
 * Format full recipes section with all details
 */
function formatFullRecipesSection(
  byDay: Record<DayOfWeek, MealPlanAssignment[]>
): string | null {
  const sections: string[] = [];
  const seenRecipes = new Set<string>();

  // Section header
  sections.push(createMarkdownHorizontalRule());
  sections.push(createMarkdownHeading("Recipes", 2));

  DAYS_ORDER.forEach((day) => {
    const dayAssignments = byDay[day];
    dayAssignments.forEach((assignment) => {
      // Skip duplicates (same recipe used multiple times)
      if (seenRecipes.has(assignment.recipe.id)) return;
      seenRecipes.add(assignment.recipe.id);

      const recipeSection = formatRecipeForMealPlan(assignment, day);
      sections.push(recipeSection);
    });
  });

  // If no recipes, return null
  if (sections.length <= 2) return null;

  return joinSections(...sections);
}

/**
 * Format a single recipe within the meal plan
 */
function formatRecipeForMealPlan(
  assignment: MealPlanAssignment,
  day: DayOfWeek
): string {
  const { recipe, cook } = assignment;
  const sections: string[] = [];

  // Recipe title with day
  sections.push(createMarkdownHeading(`${day}: ${recipe.title}`, 3));

  // Meta info
  const metaParts: string[] = [];
  if (cook) {
    metaParts.push(`${bold("Cook:")} ${cook}`);
  }
  if (recipe.prep_time) {
    metaParts.push(`${bold("Prep:")} ${recipe.prep_time}`);
  }
  if (recipe.cook_time) {
    metaParts.push(`${bold("Cook Time:")} ${recipe.cook_time}`);
  }
  if (metaParts.length > 0) {
    sections.push(metaParts.join(" | "));
  }

  // Ingredients
  if (recipe.ingredients && recipe.ingredients.length > 0) {
    sections.push(createMarkdownHeading("Ingredients", 4));
    sections.push(createMarkdownList(recipe.ingredients));
  }

  // Instructions
  if (recipe.instructions && recipe.instructions.length > 0) {
    sections.push(createMarkdownHeading("Instructions", 4));
    sections.push(createMarkdownList(recipe.instructions, true));
  }

  return joinSections(...sections);
}

/**
 * Generate filename for meal plan export
 */
export function generateMealPlanFilename(weekRange: string): string {
  const slug = formatDateRangeForFilename(weekRange);
  return `meal-plan-${slug}.md`;
}

/**
 * Export and download a meal plan as markdown
 */
export function downloadMealPlanAsMarkdown(options: MealPlanMarkdownOptions): void {
  const content = generateMealPlanMarkdown(options);
  const filename = generateMealPlanFilename(options.weekRange);
  downloadMarkdownFile(content, filename);
}
