"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Mail, Calendar, Download, ArrowLeft, Loader2, ShoppingCart } from "lucide-react";
import { toast } from "sonner";
import { useRouter } from "next/navigation";
import { formatWeekRange } from "@/types/meal-plan";
import type { DayOfWeek } from "@/types/meal-plan";

interface Recipe {
  id: string;
  title: string;
  recipe_type: string;
  prep_time: string | null;
  cook_time: string | null;
  ingredients: string[];
  instructions: string[];
}

interface Assignment {
  id: string;
  recipe_id: string;
  day_of_week: DayOfWeek;
  cook: string | null;
  recipe: Recipe;
}

interface FinalizeActionsProps {
  weekStart: Date;
  assignments: Assignment[];
  weekStartStr: string;
}

export function FinalizeActions({
  weekStart,
  assignments,
  weekStartStr,
}: FinalizeActionsProps) {
  const router = useRouter();
  const [isSending, setIsSending] = useState(false);
  const [isAddingToCalendar, setIsAddingToCalendar] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);

  const handleSendEmail = async () => {
    if (assignments.length === 0) {
      toast.error("No meals to send");
      return;
    }

    setIsSending(true);
    try {
      const response = await fetch("/api/send-shopping-list", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          weekRange: formatWeekRange(weekStart),
          weekStart: weekStartStr,
          items: assignments.map((a) => ({
            recipe: a.recipe,
            cook: a.cook,
            day: a.day_of_week,
          })),
        }),
      });

      const result = await response.json();
      if (!response.ok) {
        toast.error(result.error || "Failed to send plan");
      } else {
        toast.success(result.message || "Plan sent!");
        // Refresh to update sent status
        router.refresh();
      }
    } catch {
      toast.error("Failed to send plan");
    } finally {
      setIsSending(false);
    }
  };

  const handleAddToCalendar = async () => {
    if (assignments.length === 0) {
      toast.error("No meals to add to calendar");
      return;
    }

    setIsAddingToCalendar(true);
    try {
      const response = await fetch("/api/google-calendar/create-events", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          weekRange: formatWeekRange(weekStart),
          items: assignments.map((a) => ({
            recipe: a.recipe,
            cook: a.cook,
            day: a.day_of_week,
          })),
        }),
      });

      const result = await response.json();
      if (!response.ok) {
        toast.error(result.error || "Failed to add to calendar");
      } else if (result.eventsCreated > 0) {
        toast.success(`Created ${result.eventsCreated} calendar events!`);
      } else {
        toast.info(
          "No events created. Check Google Calendar connection in Settings."
        );
      }
    } catch {
      toast.error("Failed to add to calendar");
    } finally {
      setIsAddingToCalendar(false);
    }
  };

  const handleDownload = () => {
    if (assignments.length === 0) {
      toast.error("No meals to download");
      return;
    }

    setIsDownloading(true);

    try {
      // Generate text file
      let text = `Meal Plan - ${formatWeekRange(weekStart)}\n`;
      text += "=".repeat(50) + "\n\n";

      // Group by day
      const days: DayOfWeek[] = [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
        "Sunday",
      ];

      const byDay: Record<string, Assignment[]> = {};
      assignments.forEach((a) => {
        if (!byDay[a.day_of_week]) {
          byDay[a.day_of_week] = [];
        }
        byDay[a.day_of_week].push(a);
      });

      days.forEach((day) => {
        const dayAssignments = byDay[day];
        if (dayAssignments && dayAssignments.length > 0) {
          text += `${day}\n`;
          text += "-".repeat(30) + "\n";
          dayAssignments.forEach((a) => {
            text += `• ${a.recipe.title}`;
            if (a.cook) text += ` (${a.cook})`;
            text += "\n";
          });
          text += "\n";
        }
      });

      // Add shopping list
      text += "\n\nSHOPPING LIST\n";
      text += "=".repeat(50) + "\n\n";

      const allIngredients = new Set<string>();
      assignments.forEach((a) => {
        if (a.recipe.ingredients) {
          a.recipe.ingredients.forEach((ing) => allIngredients.add(ing));
        }
      });

      Array.from(allIngredients).forEach((ing, index) => {
        text += `${index + 1}. ${ing}\n`;
      });

      text += "\n\nGenerated by your meal planning app\n";

      // Create and download file
      const blob = new Blob([text], { type: "text/plain" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `meal-plan-${formatWeekRange(weekStart)
        .replace(/\s/g, "-")
        .toLowerCase()}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      toast.success("Meal plan downloaded!");
    } catch {
      toast.error("Failed to download");
    } finally {
      setIsDownloading(false);
    }
  };

  const handleBackToEdit = () => {
    router.push(`/app/plan?week=${weekStartStr}`);
  };

  const handleEditShoppingList = () => {
    router.push("/app/shop");
  };

  return (
    <Card className="border-t-2 border-primary/20 sticky bottom-0 md:bottom-4 z-10 shadow-lg">
      <CardContent className="p-4">
        <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-3">
          {/* Back button */}
          <Button
            variant="ghost"
            onClick={handleBackToEdit}
            className="w-full sm:w-auto"
          >
            <ArrowLeft className="h-4 w-4 mr-2" />
            Edit Plan
          </Button>

          <div className="flex-1" />

          {/* Action buttons */}
          <div className="flex flex-col sm:flex-row gap-2">
            <Button
              variant="outline"
              onClick={handleDownload}
              disabled={isDownloading}
              className="w-full sm:w-auto"
            >
              {isDownloading ? (
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              ) : (
                <Download className="h-4 w-4 mr-2" />
              )}
              Download
            </Button>

            <Button
              variant="outline"
              onClick={handleAddToCalendar}
              disabled={isAddingToCalendar}
              className="w-full sm:w-auto"
            >
              {isAddingToCalendar ? (
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              ) : (
                <Calendar className="h-4 w-4 mr-2" />
              )}
              Add to Calendar
            </Button>

            <Button
              variant="outline"
              onClick={handleEditShoppingList}
              className="w-full sm:w-auto"
            >
              <ShoppingCart className="h-4 w-4 mr-2" />
              Edit Shopping List
            </Button>

            <Button
              onClick={handleSendEmail}
              disabled={isSending}
              className="w-full sm:w-auto"
            >
              {isSending ? (
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              ) : (
                <Mail className="h-4 w-4 mr-2" />
              )}
              Send Plan
            </Button>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}

